baseURL: 'http://romrawinjp.github.io/'
languageCode: 'en-us'
title: 'Romrawin Chumpu'
theme: "PaperMod"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: CV
                  url: cv
                  weight: 1
                # - name: Publications
                #   url: cv/#publications
                  # weight: 5
                # - name: Archive
                #   url: archives
                #   weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 15
                - name: Artworks
                  url: artworks/
                  weight: 3
                - name: Project
                  url: project/
                  weight: 2
                - name: ❤️
                  url: /chill-blog
                  weight: 20
                # - name: WiKi
                #   url: https://github.com/adityatelange/hugo-PaperMod/wiki/
                # - name: Discord
                #   url: https://discord.gg/ahpmTvhVmp
    # fr:
    #     languageName: ":fr:"
    #     languageAltTitle: French
    #     weight: 2
    #     title: PaperModL2
    #     taxonomies:
    #       category: FRcategories
    #       tag: FRtags
    #       series: FRseries
    #     profileMode:
    #         enabled: true
    #         title: PaperMod
    #         imageUrl: "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f317.svg"
    #         imageTitle: ProfileMode image
    #         # imageWidth: 120
    #         # imageHeight: 120
    #         subtitle: "☄️ Fast | ☁️ Fluent | 🌙 Smooth | 📱 Responsive"
    #         buttons:
    #             - name: Blog
    #               url: posts
    #             - name: Profile Mode
    #               url: https://github.com/adityatelange/hugo-PaperMod/wiki/Features#profile-mode
    #     menu:
    #         main:
    #             - name: Archive
    #               url: archives/
    #               weight: 5
    #             - name: FRTags
    #               url: frtags
    #               weight: 10
    #             - name: FRCategories
    #               url: frcategories
    #               weight: 10
    #             - name: FRSeries
    #               url: frseries
    #               weight: 10
    #             - name: NullLink
    #               url: "#"

    # fa:
    #     languagedirection: rtl
    #     weight: 3
    #     title: PaperMod RTL
    #     homeInfoParams:
    #         Title: "Hi there \U0001F44B"
    #         Content: Welcome to RTL layout
    #     taxonomies:
    #       category: FAcategories
    #       tag: FAtags
    #       series: FAseries
    #     menu:
    #         main:
    #             - name: FATags
    #               url: fatags
    #               weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Romrawin Chumpu's Personal Webpage"
    author: Romrawin Chumpu
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShareButtons: ["linkedin", "twitter"] 
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    comments: true
    images: ["/content/images/project/crochet/star_parts.jpg"]

    profileMode:
        enabled: false
        title: Romrawin Chumpu
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "Welcome to Jin's Blog" 
        Content: >
            - 🌳 Learning little by little is a part of big growing up 

            - 👩‍💻 [CV is here](./cv) 
    socialIcons:
        - name: github
          url: "https://github.com/romrawinjp"
        # - name: instagram
        #   url: "https://instagram.com/romrawinjp"
        # - name: facebook
        #   url: "https://facebook.com/romrawin.chumpu/"
        - name: twitter
          url: "https://twitter.com/romrawinjp"        
        # - name: linkedin
        #   url: "https://www.linkedin.com/in/romrawin-chumpu/"
        - name: googlescholar
          url: "https://scholar.google.co.th/citations?user=d2mMM0AAAAAJ&hl=en"
        # - name: researchgate
        #   url: "https://www.researchgate.net/profile/Romrawin-Chumpu"
        - name: medium
          url: "https://romrawin.medium.com/"
    # editPost:
    #     URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
    #     Text: "Suggest Changes" # edit text
    #     appendFilePath: true # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    assets:
        disableHLJS: true
        favicon: "favicon.ico"
        favicon16x16: "favicon-16x16.png"
        favicon32x32: "favicon-32x32.png"
        apple_touch_icon: "apple-touch-icon.png"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: true
        style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true